/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Colors using CSS custom properties
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary-500)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          DEFAULT: 'var(--color-secondary-500)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          DEFAULT: 'var(--color-success-500)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          DEFAULT: 'var(--color-warning-500)',
        },
        danger: {
          50: 'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          200: 'var(--color-danger-200)',
          300: 'var(--color-danger-300)',
          400: 'var(--color-danger-400)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          800: 'var(--color-danger-800)',
          900: 'var(--color-danger-900)',
          DEFAULT: 'var(--color-danger-500)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
          DEFAULT: 'var(--color-neutral-500)',
        },
        // Semantic colors
        background: 'var(--color-neutral-950)',
        surface: 'var(--color-neutral-900)',
        border: 'var(--color-neutral-700)',
        text: {
          primary: 'var(--color-neutral-50)',
          secondary: 'var(--color-neutral-300)',
          muted: 'var(--color-neutral-400)',
        },
      },
      // Typography
      fontFamily: {
        sans: 'var(--typography-fontFamily-sans)',
        serif: 'var(--typography-fontFamily-serif)',
        mono: 'var(--typography-fontFamily-mono)',
      },
      fontSize: {
        xs: 'var(--typography-fontSize-xs)',
        sm: 'var(--typography-fontSize-sm)',
        base: 'var(--typography-fontSize-base)',
        lg: 'var(--typography-fontSize-lg)',
        xl: 'var(--typography-fontSize-xl)',
        '2xl': 'var(--typography-fontSize-2xl)',
        '3xl': 'var(--typography-fontSize-3xl)',
        '4xl': 'var(--typography-fontSize-4xl)',
        '5xl': 'var(--typography-fontSize-5xl)',
        '6xl': 'var(--typography-fontSize-6xl)',
      },
      fontWeight: {
        thin: 'var(--typography-fontWeight-thin)',
        light: 'var(--typography-fontWeight-light)',
        normal: 'var(--typography-fontWeight-normal)',
        medium: 'var(--typography-fontWeight-medium)',
        semibold: 'var(--typography-fontWeight-semibold)',
        bold: 'var(--typography-fontWeight-bold)',
        extrabold: 'var(--typography-fontWeight-extrabold)',
      },
      lineHeight: {
        none: 'var(--typography-lineHeight-none)',
        tight: 'var(--typography-lineHeight-tight)',
        snug: 'var(--typography-lineHeight-snug)',
        normal: 'var(--typography-lineHeight-normal)',
        relaxed: 'var(--typography-lineHeight-relaxed)',
        loose: 'var(--typography-lineHeight-loose)',
      },
      // Spacing
      spacing: {
        px: 'var(--spacing-px)',
        0: 'var(--spacing-0)',
        0.5: 'var(--spacing-0-5)',
        1: 'var(--spacing-1)',
        1.5: 'var(--spacing-1-5)',
        2: 'var(--spacing-2)',
        2.5: 'var(--spacing-2-5)',
        3: 'var(--spacing-3)',
        3.5: 'var(--spacing-3-5)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
        9: 'var(--spacing-9)',
        10: 'var(--spacing-10)',
        11: 'var(--spacing-11)',
        12: 'var(--spacing-12)',
        14: 'var(--spacing-14)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
        28: 'var(--spacing-28)',
        32: 'var(--spacing-32)',
        36: 'var(--spacing-36)',
        40: 'var(--spacing-40)',
        44: 'var(--spacing-44)',
        48: 'var(--spacing-48)',
        52: 'var(--spacing-52)',
        56: 'var(--spacing-56)',
        60: 'var(--spacing-60)',
        64: 'var(--spacing-64)',
        72: 'var(--spacing-72)',
        80: 'var(--spacing-80)',
        96: 'var(--spacing-96)',
      },
      // Border Radius
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-DEFAULT)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      // Box Shadow
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-DEFAULT)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'var(--shadow-none)',
      },
      // Background Gradients
      backgroundImage: {
        'gradient-primary': 'var(--background-gradients-primary)',
        'gradient-secondary': 'var(--background-gradients-secondary)',
        'gradient-success': 'var(--background-gradients-success)',
        'gradient-warning': 'var(--background-gradients-warning)',
        'gradient-danger': 'var(--background-gradients-danger)',
        'gradient-hero': 'var(--background-gradients-hero)',
        'gradient-subtle': 'var(--background-gradients-subtle)',
        'pattern-dots': 'var(--background-patterns-dots)',
        'pattern-grid': 'var(--background-patterns-grid)',
        'pattern-noise': 'var(--background-patterns-noise)',
        'pattern-diagonal': 'var(--background-patterns-diagonal)',
      },
      // Backdrop Filters
      backdropBlur: {
        sm: 'var(--background-backdrop-blur-sm)',
        md: 'var(--background-backdrop-blur-md)',
        lg: 'var(--background-backdrop-blur-lg)',
        xl: 'var(--background-backdrop-blur-xl)',
      },
      backdropOpacity: {
        light: 'var(--background-backdrop-opacity-light)',
        medium: 'var(--background-backdrop-opacity-medium)',
        heavy: 'var(--background-backdrop-opacity-heavy)',
      },
      // Animation
      animation: {
        'fade-in': 'fadeIn var(--animation-duration-base) var(--animation-easing-easeOut)',
        'fade-out': 'fadeOut var(--animation-duration-base) var(--animation-easing-easeIn)',
        'slide-up': 'slideUp var(--animation-duration-base) var(--animation-easing-easeOut)',
        'slide-down': 'slideDown var(--animation-duration-base) var(--animation-easing-easeOut)',
        'slide-left': 'slideLeft var(--animation-duration-base) var(--animation-easing-easeOut)',
        'slide-right': 'slideRight var(--animation-duration-base) var(--animation-easing-easeOut)',
        'scale-in': 'scaleIn var(--animation-duration-fast) var(--animation-easing-easeOut)',
        'scale-out': 'scaleOut var(--animation-duration-fast) var(--animation-easing-easeIn)',
        'pulse': 'pulse var(--animation-duration-slow) var(--animation-easing-ease) infinite',
        'bounce': 'bounce var(--animation-duration-slower) var(--animation-easing-bouncy) infinite',
        'spin': 'spin var(--animation-duration-slower) var(--animation-easing-linear) infinite',
        'ping': 'ping var(--animation-duration-slower) var(--animation-easing-ease) infinite',
      },
      // Keyframes
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        bounce: {
          '0%, 20%, 53%, 80%, 100%': { transform: 'translate3d(0,0,0)' },
          '40%, 43%': { transform: 'translate3d(0, -30px, 0)' },
          '70%': { transform: 'translate3d(0, -15px, 0)' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        ping: {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
      },
      transitionDuration: {
        fast: 'var(--animation-duration-fast)',
        base: 'var(--animation-duration-base)',
        slow: 'var(--animation-duration-slow)',
        slower: 'var(--animation-duration-slower)',
      },
      transitionTimingFunction: {
        linear: 'var(--animation-easing-linear)',
        ease: 'var(--animation-easing-ease)',
        in: 'var(--animation-easing-easeIn)',
        out: 'var(--animation-easing-easeOut)',
        'in-out': 'var(--animation-easing-easeInOut)',
        bouncy: 'var(--animation-easing-bouncy)',
        elastic: 'var(--animation-easing-elastic)',
      },
      // Interactive state utilities
      scale: {
        'hover': 'var(--interaction-hover-scale)',
        'active': 'var(--interaction-active-scale)',
      },
      brightness: {
        'hover': 'var(--interaction-hover-brightness)',
        'active': 'var(--interaction-active-brightness)',
      },
      // Screens (breakpoints)
      screens: {
        sm: 'var(--breakpoint-sm)',
        md: 'var(--breakpoint-md)',
        lg: 'var(--breakpoint-lg)',
        xl: 'var(--breakpoint-xl)',
        '2xl': 'var(--breakpoint-2xl)',
      },
    },
  },
  plugins: [],
}